# Generated by Django 4.1.7 on 2023-03-01 21:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicelog', '0003_alter_session_focus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='sessions',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='session',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
