# Generated by Django 4.1.7 on 2023-03-16 01:53

from django.db import migrations, models
import practicelog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('practicelog', '0005_session_moods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(validators=[practicelog.validators.validate_date]),
        ),
    ]
