# Generated by Django 4.1.7 on 2023-03-16 01:56

from django.db import migrations, models
import practicelog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('practicelog', '0006_alter_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(validators=[practicelog.validators.validate_duration]),
        ),
    ]
