# Generated by Django 4.1.7 on 2023-03-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='excerpt',
            field=models.TextField(max_length=300),
        ),
    ]
